#!groovy

pipeline {
    agent none
    stages {
        stage('Build .deb (meta-)packages') {
            agent {
                dockerfile {
                    dir 'deb-packager'
                }
            }
            steps {
                emailext (
                    subject: "STARTED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
                    body: """<p>STARTED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]':</p>
                      <p>Will deploy to ${params.DEPLOY_TARGET}</p>
                      <p>Check console output at &QUOT;<a href='${env.BUILD_URL}'>${env.JOB_NAME} [${env.BUILD_NUMBER}]</a>&QUOT;</p>""",
                    to: "buildmasters@contentserv.com"
                )
                dir('metapackage-build/debian') {
                    checkout poll: false, scm: [$class: 'GitSCM', \
                        branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, \
                        extensions: [], submoduleCfg: [], \
                        userRemoteConfigs: [[credentialsId: 'dfa6f5a3-608c-4f05-bb23-3c096c4cc430', \
                        url: 'https://mrjenkins@git.contentserv.intern/DevOps/Deployment/CS-Deb-Metapackage']]]
                }
                sh 'rm -f *.deb *.changes || true'
                sh 'cd metapackage-build && dpkg-buildpackage -b -i -uc -us'
            }
        }
        stage('Submit to APT Repository') {
            agent any
            steps {
                sh 'rm -f /mnt/apt-incoming/* || true'
                sh 'mv -f *.deb /mnt/apt-incoming'
                sh 'mv -f *.changes /mnt/apt-incoming'
                sh "ssh root@git.contentserv.intern /usr/local/bin/add-to-repo bionic '${params.DEPLOY_TARGET}'"
            }
        }
    }
    post {
        success {
            emailext (
                subject: "SUCCESSFUL: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
                body: """<p>SUCCESSFUL: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]':</p>
                  <p>Check console output at &QUOT;<a href='${env.BUILD_URL}'>${env.JOB_NAME} [${env.BUILD_NUMBER}]</a>&QUOT;</p>""",
                to: "buildmasters@contentserv.com"
            )
        }
        failure {
            emailext (
                subject: "FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
                body: """<p>FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]':</p>
                  <p>Check console output at &QUOT;<a href='${env.BUILD_URL}'>${env.JOB_NAME} [${env.BUILD_NUMBER}]</a>&QUOT;</p>""",
                to: "buildmasters@contentserv.com"
            )
        }
    }
}

