index.php        var/lib/contentserv-cs
admin            var/lib/contentserv-cs
admin.local      var/lib/contentserv-cs
debian/additions/etc/apache2/conf-available/contentserv.conf            etc/apache2/conf-available
debian/additions/etc/apache2/sites-available/cs-vhost-template.conf     var/lib/contentserv-cs/admin/core/samples/apache-vhost
debian/additions/etc/php/7.0/mods-available                             etc/php/7.0
debian/additions/etc/mysql                                              etc
debian/additions/etc/supervisor                                         etc