#!groovy

pipeline {
    agent {
        dockerfile { 
            dir 'xenial-backports-builder'
            args '-v /Jenkins-CI/tools:/Jenkins-CI/tools' 
        }
    }
    stages {
        stage('Build imagemagick .deb packages for Ubuntu Xenial Xerus (16.04 LTS) backported from zesty') {
            steps {
                dir('ImageMagick') {
                    checkout poll: false, scm: [$class: 'GitSCM', \
                        branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, \
                        extensions: [], submoduleCfg: [], \
                        userRemoteConfigs: [[credentialsId: 'dfa6f5a3-608c-4f05-bb23-3c096c4cc430', \
                        url: 'https://mrjenkins@git.contentserv.intern/Development/3rdparty/ImageMagickZestyToXenialBackport']]]
                }
                sh 'cd ImageMagick && dpkg-buildpackage -b -i -uc -us'
            }
        }
    }
}
