---
csalive_zabbix_serveractive: 'zbx-proxy1-ush.sasg.de'
csalive_zabbix_pidfile: '/var/run/zabbix/zabbix_agentd.pid'
csalive_zabbix_logfile: '/var/log/zabbix-agent/zabbix_agentd.log'
csalive_zabbix_logfilesize: 0
csalive_zabbix_debuglevel: 1
csalive_zabbix_server: ''
csalive_zabbix_startagents: 3
