---
# geeringguy.apache role variables
apache_remove_default_vhost: true

apache_listen_ip: "*"
apache_listen_port: 80
apache_listen_port_ssl: 443

apache_mods_enabled:
  - rewrite.load
  - php5.6.load
  - ssl.load
  - deflate.load
  - expires.load
  - authz_host.load
  - dir.load
  - mime.load
  - status.load

apache_vhosts:
  - servername: "jumbo-prod.contentsphere.com"
    serveralias: "localhost"
    documentroot: "/var/www/CONTENTSERV/"
    extra_parameters: |
        <Directory /var/www/CONTENTSERV/>
          Options FollowSymLinks MultiViews
          AllowOverride All
          Require all granted
          <If "!-R '127.0.0.1' && !-R '::1'">
            RedirectMatch permanent ^(.*)$ https://jumbo-prod.contentsphere.com$1
          </If>
        </Directory>

  - servername: "jumbo-prod-candidate.contentsphere.com"
    documentroot: "/var/www/CONTENTSERV/"
    extra_parameters: |
        <Directory /var/www/CONTENTSERV/>
          Options FollowSymLinks MultiViews
          AllowOverride All
          Require all granted
          RedirectMatch permanent ^(.*)$ https://jumbo-prod.contentsphere.com$1
        </Directory>


apache_vhosts_ssl:
  - servername: "jumbo-prod.contentsphere.com"
    serveralias: "localhost"
    documentroot: "/var/www/CONTENTSERV/"
    certificate_file: "/etc/apache2/ssl/certificate.crt"
    certificate_key_file: "/etc/apache2/ssl/certificate.key"
    extra_parameters: |
        <Directory /var/www/CONTENTSERV/>
          Options FollowSymLinks MultiViews
          AllowOverride All
          Require all granted
        </Directory>

  - servername: "jumbo-prod-candidate.contentsphere.com"
    documentroot: "/var/www/CONTENTSERV/"
    certificate_file: "/etc/apache2/ssl/certificate.crt"
    certificate_key_file: "/etc/apache2/ssl/certificate.key"
    extra_parameters: |
        <Directory /var/www/CONTENTSERV/>
          Options FollowSymLinks MultiViews
          AllowOverride All
          Require all granted
          RedirectMatch permanent ^(.*)$ https://jumbo-prod.contentsphere.com$1
        </Directory>


# Create user accounts (for Jumbo SFTP access), note "$6$" SHA512 hashes
system_users:
  - username: "sapftp"
    uid: 1002
    comment: ""
    password: "$6$4P9cZ/VD$mD2gzalWG9nCezYIUg6fRZ3mr0X1hhxyDmyBC31U6TnGopq2ymeoz0xypRjD45jgAjRmEzSvCMe32ljlycO0H."
    home: "/var/www/CONTENTSERV/Jumbo_Prod/jumbo/volumes/SAP/Hotfolder"
    shell: "/bin/bash"
  - username: "mamftp"
    uid: 1001
    comment: ""
    password: "$6$Rg2gedFQ$Hj3AI2ga47YwS7xF6lryZVQdwyoEfoAVlPAXUrxqRhJGekpUBBReP3wDAKKOAB7BsOz5DTrc4ixw0SdVuvb3M0"
    home: "/var/www/CONTENTSERV/Jumbo_Prod/jumbo/volumes/Images/AssetReplacement/AssetReplacement_HotFolder"
    shell: "/bin/bash"
  - username: "tms_supertext"
    uid: 1003
    comment: ""
    password: "$6$.Na7jeNv$wE.7MEZYw4gssiRR6OsJ212eTQDc1rpm4gQGGhNMTTiG92jTJp7CZofDUhKLJtDEtkGHNfYC9cG3zyevmQayl/"
    home: "/var/www/CONTENTSERV/Jumbo_Prod/jumbo/volumes/Home/TMS"
    shell: "/bin/bash"
  - username: "mdebildarchiv"
    uid: 1004
    comment: ""
    password: "$6$Lqj7nYPF$qm.FMmK8JVpATdAeP/s1mNBFe/EjSY6CLLRu7NTM4FoEZvn7heIUBIALAhIDz1XusAa0a81veRQKw4VLlE.861"
    home: "/var/www/CONTENTSERV/Jumbo_Prod/jumbo/volumes/SAP/MDE-Bilder"
    shell: "/bin/bash"
  - username: "pimde"
    uid: 1005
    comment: ""
    password: "$6$5dyZQ4fL$U2Sld7U7cd25.2pG5YY736r1.pUTUfEsjAB3swdo2TqSywaE9rzLLsJX5FSEJk2muAXYnPmuvkuy0GlX5HwkX0"
    home: "/var/www/CONTENTSERV/Jumbo_Prod/jumbo/volumes/SAP/MDE-Bilder/2_PI_MDE"
    shell: "/bin/bash"
  - username: "pdfftp"
    uid: 1006
    comment: ""
    password: "$6$5NvqkOir$R0cBxnO5LunQzq/7z15/QulPyFY9bY9TaoJijHfD7ueAY3jPprmP5eCKQ22eQX3lgN9KyEc.2ARoLwhD6xNmR1"
    home: "/var/www/CONTENTSERV/Jumbo_Prod/jumbo/volumes/Images/Dokumente"
    shell: "/bin/bash"
  - username: "thomet"
    uid: 1007
    comment: "Stefan Thomet"
    password: "$6$leIQgCw1$J7sozbQtYjU1b2YadYI06TACTCsefd2ksrwohbc/rxzbgd4ZQ9bEWnbVhoE9qiAn6F6U8Oku.G37/2abAduD61"
    home: "/var/www/CONTENTSERV/Jumbo_Prod/jumbo/volumes"
    shell: "/bin/bash"
  - username: "cs"
    uid: 1000
    comment: "cs"
    password: "$6$f/RulKvv$R8az6jAAJZFl5jzBbY/4EasvrdF8K9CnaZ3GUWhwoV9kIE1lcfyUIXPjeZHoSlnjTAOxgERxCWFVU.XWPfLHd0"
    home: "/home/cs"
    shell: "/bin/bash"
  - username: "mettler"
    uid: 1008
    comment: "Marcel Mettler"
    password: "$6$5qRyzo3A$DBV/Xzy6J0Kg/86tU2HMKiB7UIWrxsc0f6gSiZLaEnZs.6WEf74q4.RuOFu6YnhKn3p1fXRk4sWp0krLpHLfS."
    home: "/var/www/CONTENTSERV/Jumbo_Prod/jumbo/volumes"
    shell: "/bin/bash"

# CSAlive Zabbix agent parameters
csalive_zabbix_userparameter: 'CS[*],/usr/bin/curl -s -m 30 "http://localhost/Jumbo_Prod/admin/rest/csalive/getmonitorstatusdata/?autoclean=2"'  
csalive_zabbix_hostname: 'JUMBO_PROD_CS'
csalive_zabbix_extras: |
    UserParameter=ApacheStats[*],/etc/zabbix/apachestats.php 127.0.0.1 80
