---
- name: Install/update incron
  apt:
    name: incron
    update_cache: yes
    state: latest
    cache_valid_time: 900

- name: Install shell scripts for use by incron
  copy:
    src: ./files/{{ ansible_nodename }}/opt/incron/
    dest: /opt/incron
    owner: root
    group: root
    mode: 0755

- name: Ensure incron supplementary scripts are executable
  file:
    name: /opt/incron
    owner: root
    group: root
    mode: 0755
    recurse: yes

- name: Allow root user to use incron
  lineinfile:
    path: /etc/incron.allow
    line: 'root'
    state: present
  notify: Restart incron

- name: Copy root's incron table
  copy:
    src: ./files/{{ ansible_nodename }}/var/spool/incron/root
    dest: /var/spool/incron
    owner: root
    group: root
  notify: Restart incron
