<?php 
$date='2018-07-02';
$csVersion='CS16.0';
$branch='CS16.0.14';
$revision='58729';
$repository="https://svn.contentserv.com/development/tags/CS16/CS16.0/stable/admin";
$project='jumbo';
$customer='JUMBO AG';
$expiration='2027-07-18';
$orderNumber='';
if (!isset($licenseRecordData)) $licenseRecordData = array();
$licenseRecordData= $licenseRecordData + array (
  'Database:-ContentTable' => 'jp_',
  'Database:-Host' => '192.168.135.20',
  'Database:-Name' => 'jumbo_prod',
  'Database:-Password' => 'YS92OXd0I35rd0Ro',
  'Database:-User' => 'dbroot',
  'WebServer:-ExternalBasePath' => '/Jumbo_Prod/',
  'WebServer:-ExternalPort' => '443',
  'WebServer:-ExternalProtocol' => 'https',
  'WebServer:-ExternalServerName' => 'jumbo-prod.contentsphere.com',
  'WebServer:-InternalBasePath' => '/Jumbo_Prod/',
  'WebServer:-InternalPort' => '80',
  'WebServer:-InternalProtocol' => 'http',
  'WebServer:-InternalServerName' => 'localhost',
  'WebServer:-InternalWebserverPassword' => '',
  'WebServer:-InternalWebserverUser' => '',
  'core:-CSLicenseRecordID' => '1',
  'core:-CSNetUser' => 'azettl@contentserv.com',
  'core:-LicenseKey' => '937f5c92205e',
  'core:-OrderedLicenseID' => '2017-823-94f',
  'core:AlternativeServerName' => '192.168.135.19,217.114.215.196,jumbo-prod.contentsphere.com,jumbo-prod-candidate.contentsphere.com,217.114.215.201',
  'core:EULA' => '1',
  'core:ProjectName' => 'jumbo',
  'core:ServerName' => 'localhost',
  'core:ServerPath' => '/var/www/CONTENTSERV/Jumbo_Prod',
  'core:ServerType' => 'prod',
  'core:lic5' => '48c6cc2ecf118170aa4b963c371d856e',
);
