---
# geeringguy.apache role variables
apache_remove_default_vhost: true

apache_listen_ip: "*"
apache_listen_port: 80
apache_listen_port_ssl: 443

apache_mods_enabled:
  - rewrite.load
  - php5.6.load
  - ssl.load
  - deflate.load
  - expires.load
  - authz_host.load
  - dir.load
  - mime.load
  - status.load

apache_vhosts:
  - servername: "jumbo-acceptance.contentsphere.com"
    serveralias: "localhost"
    documentroot: "/var/www/CONTENTSERV/"
    extra_parameters: |
        <Directory /var/www/CONTENTSERV/>
          Options FollowSymLinks MultiViews
          AllowOverride All
          Require all granted
          <If "!-R '127.0.0.1' && !-R '::1'">
            RedirectMatch permanent ^(.*)$ https://jumbo-acceptance.contentsphere.com$1
          </If>
        </Directory>


apache_vhosts_ssl:
  - servername: "jumbo-acceptance.contentsphere.com"
    serveralias: "localhost"
    documentroot: "/var/www/CONTENTSERV/"
    certificate_file: "/etc/apache2/ssl/certificate.crt"
    certificate_key_file: "/etc/apache2/ssl/certificate.key"
    extra_parameters: |
        <Directory /var/www/CONTENTSERV/>
          Options FollowSymLinks MultiViews
          AllowOverride All
          Require all granted
        </Directory>


# Create user accounts (for Jumbo SFTP access), note "$6$" SHA512 hashes
system_users:
  - username: "sapftp"
    uid: 1002
    comment: ""
    password: "$6$dsw.MW2/$LtL5GLvIrERc9nk2S9hM6mI.kBb1aw2l9PbjdaWE6dfqLAIRIYzMZqV6afDizwzKy1nHrtrB3L01ArkmarKs31"
    home: "/var/www/CONTENTSERV/Jumbo_Acceptance/jumbo/volumes/SAP/Hotfolder"
    shell: "/bin/bash"
  - username: "mamftp"
    uid: 1001
    comment: ""
    password: "$6$R6xTUD6l$ou9UiV/oKkJWgB4esbMzXB7sM8YCS72eQjHvgVO4siJLDtBJrzz9BNRyNkfpBjas6kjrfQYTlC8LLT3wZ02iG1" 
    home: "/var/www/CONTENTSERV/Jumbo_Acceptance/jumbo/volumes/Images/AssetReplacement/AssetReplacement_HotFolder"
    shell: "/bin/bash"
  - username: "tms_supertext"
    uid: 1003
    comment: ""
    password: "$6$aXQLmUCI$D1BuvSfR01mnXqaO4icYje/KZ7uC5a3sGFIiTHxUt7K8PM3hDrPao4JkmHItYxqeVAiuGaZHJ6y7tPi2P9Lhc/" 
    home: "/var/www/CONTENTSERV/Jumbo_Acceptance/jumbo/volumes/Home/TMS"
    shell: "/bin/bash"
  - username: "mdebildarchiv"
    uid: 1004
    comment: ""
    password: "$6$15fp5v6s$BPKEn12drWixQOsZtGgfE7aLo.lmXPMRIEqBaz85KkWdd3fpSaHydXwGSINTcDLgEYqmWGhaVG.RSsQ/0VXVR0"
    home: "/var/www/CONTENTSERV/Jumbo_Acceptance/jumbo/volumes/SAP/MDE-Bilder"
    shell: "/bin/bash"
  - username: "pimde"
    uid: 1005
    comment: ""
    password: "$6$tAe7UsUc$140CcbW233XMkiveIS7Lgk6Me5qSsEbjALEAJ6gaWrb6PNo7rok.LXHgdjt3xdVEZQgzCRcMIax4C8H5Wajrb"
    home: "/var/www/CONTENTSERV/Jumbo_Acceptance/jumbo/volumes/SAP/MDE-Bilder/2_PI_MDE"
    shell: "/bin/bash"
  - username: "pdfftp"
    uid: 1006
    comment: ""
    password: "$6$GZZDSJw1$ZdeJPvDmFoBnzjdFNCGxzOI/dqEXvPj.bLglXQlP7VEjKsiSG9VtTLJ7V3NOxg7MnaMILUdVSrOlcdZAu6fio0"
    home: "/var/www/CONTENTSERV/Jumbo_Acceptance/jumbo/volumes/Images/Dokumente"
    shell: "/bin/bash"
  - username: "thomet"
    uid: 1007
    comment: "Stefan Thomet"
    password: "$6$iM6zMeKN$FFcenr3oBMC3uFBnsG/vPyg5v/ISlSspeWWoes8iDAuLpPKA/cLb4LLu6x9hy9sqRy4.J2nRhvBuGl.gyg1Y.1"
    home: "/var/www/CONTENTSERV/Jumbo_Acceptance/jumbo/volumes"
    shell: "/bin/bash"
  - username: "cs"
    uid: 1000
    comment: "cs"
    password: "$6$KVJ7BMBs$YF3Jb44oL2H2dwR2s3zM0DcL0Gvg40ysgtyecRbWShyX1.2uHNV0UGn6nKvZaaUtqo4v7JyrW3alPvm/7ypZC."
    home: "/home/cs"
    shell: "/bin/bash"
  - username: "mettler"
    uid: 1008
    comment: "Marcel Mettler"
    password: "$6$GER5bFi2$X8Y6oXy/3xnuBoRa4.XsPuUWjpIt.2zTM9e65Dp2pZ5rXcNUbLf/nwxQYNAcP62RDddjq2tUcWqg299.FHK2V."
    home: "/var/www/CONTENTSERV/Jumbo_Acceptance/jumbo/volumes"
    shell: "/bin/bash"

# CSAlive Zabbix agent parameters
csalive_zabbix_userparameter: 'CS[*],/usr/bin/curl -s -m 30 "http://localhost/Jumbo_Acceptance/admin/rest/csalive/getmonitorstatusdata/?autoclean=2"'  
csalive_zabbix_hostname: 'JUMBO_ACC_CS'
csalive_zabbix_extras: |
    UserParameter=ApacheStats[*],/etc/zabbix/apachestats.php 127.0.0.1 80
